apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: assessmentingress
 annotations:
   kubernetes.io/ingress.class: kong
spec:
 rules:
 - http:
     paths:
     - path: /v1/tasks/task
       pathType: Prefix
       backend:
         service:
           name: producerrest
           port:
             number: 80
     - path: /v1/hello
       pathType: Prefix
       backend:
         service:
           name: q4yml
           port:
             number: 80
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
 name: correlation-id-assessment
config:
 header_name: TX-Request-ID
 generator: uuid#counter
 echo_downstream: true
plugin: correlation-id